version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  asterisk:
    build: ./docker/asterisk
    ports:
      - "5060:5060/udp"
      - "8088:8088"
      - "8089:8089"
    volumes:
      - ./docker/asterisk/configs:/etc/asterisk

  api:
    build: ./src/VoipDiscador.Api
    ports:
      - "5000:80"
    depends_on:
      - asterisk
      - kafka
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  webphone:
    build: ./src/Webphone
    ports:
      - "3000:3000"
    depends_on:
      - asterisk

